Trade Widget
bancorprotocol/webapp-v3 pull request #332
Opened 2022-05-16 17:42 UTC by pingustar

#236 #292 #84 #378

2022-05-30 17:02 UTC, RanCohenn requested changes
Maybe we should add limit into the widget logic, with certain separation.

Before this is merged into main we need to:

- [x] Remove the beta url
- [x] remove old swap code

2022-05-31 08:41 UTC, pingustar commented on src/elements/trade/TradeWidgetCTA.tsx
> +    // TODO handle rate 0
thanks, will fix

2022-05-31 08:44 UTC, pingustar commented
> Maybe we should add limit into the widget logic, with certain separation.

lets tackle limit in a separate issue and pr.

2022-05-31 11:58 UTC, ashachaf commented
- [ ] 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/40430285/171167623-7e27ee7a-4ed6-492e-988c-640d7c6bc63d.png">
flow:
- set trade from BNT to ETH
- enter bnt amount
- wait 1-2 seconds (before the rate appears)
- change token to DAI

expected behavior should:
- keep the input BNT amount 
- re-calculate the rate based on the input amount and destination token

2022-05-31 12:05 UTC, ashachaf commented
- [ ] handle wETH
<img width="522" alt="image" src="https://user-images.githubusercontent.com/40430285/171168779-5a770913-c084-4a0b-9a2f-f117a179d2d8.png">
reference:
https://github.com/bancorprotocol/webapp-v2/issues/210
https://github.com/bancorprotocol/webapp-v2/issues/64

2022-06-01 11:54 UTC, ashachaf commented
- [ ] make sure when selecting weth in the from, we automatically select eth as the destination token (lock it from changes)
- [ ] when clicking the switch option, set eth as the from token and reset the destination token to show "select token"

<img width="510" alt="image" src="https://user-images.githubusercontent.com/40430285/171398084-e410627c-dcbb-42b9-ade0-ff2864cb7220.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/40430285/171398123-00866ab6-b481-479a-8a4b-34cfaa135a87.png">

2022-06-01 12:10 UTC, zavelevsky approved these changes
LGTM

2022-06-02 08:46 UTC, ashachaf commented
- [ ] close "approve" popup should reset the "trade" CTA
<img width="522" alt="image" src="https://user-images.githubusercontent.com/40430285/171590499-dc3617dd-8004-43e8-989f-26fd33ddb429.png">
flow:
1. set trade from a token that requires approve
2. when the approve popup shows up, close it
expected: trade CTA to be enabled
actual: it is disabled and force to refresh

- [ ] input field shows NaN
<img width="528" alt="image" src="https://user-images.githubusercontent.com/40430285/171590929-e288690f-1462-4082-8e37-74ffe5cc96de.png">
flow:
1. set trade from a token that requires approve (only happens when view is on USD)
2. when the approve popup shows up, close it
3. change token to DAI
4. try to change input value

- [ ] select full balance on USD view input incorect values
<img width="536" alt="image" src="https://user-images.githubusercontent.com/40430285/171591196-7253db23-c74b-4e33-8b89-e1c336d13cee.png">
flow:
1. set the trade to USD view
2. select all (click the balance)
expected: see the full balance in the from token field
actual: we pull the token amount as the USD input.

2022-06-03 15:24 UTC, RanCohenn submitted a review, later dismissed
LGTM

2022-06-06 09:44 UTC, ashachaf submitted a review, later dismissed

2022-06-06 09:47 UTC, ashachaf commented
- [ ] input amount edge case
flow:
1. set input to usd
2. set $333 DAI
3. change token from DAI to ETH
expected: $333 worth of ETH
actual: the DAI token amount is used as ETH amount

2022-06-06 12:07 UTC, zavelevsky commented on src/elements/trade/TradeWidgetCTA.tsx
> +  const swapButtonText = () => {
I'd wrap with useMemo

2022-06-06 12:09 UTC, zavelevsky commented on src/elements/trade/TradeWidgetInput.tsx
> +  const inputRef = useRef<HTMLInputElement>(null);
are you trying to achieve something like this? https://reactjs.org/docs/hooks-reference.html#useimperativehandle

2022-06-07 11:57 UTC, merged