moved to use https in alchemy instead of WS
bancorprotocol/webapp-v3 pull request #491
Opened 2022-06-14 07:47 UTC by zavelevsky

2022-06-30 14:21 UTC, pingustar submitted a review, later dismissed
LGTM

2022-07-03 13:56 UTC, RanCohenn requested changes
We can remove the WS keep alive code

2022-07-04 07:32 UTC, zavelevsky commented
> We can remove the WS keep alive code

done

2022-07-04 07:37 UTC, RanCohenn approved these changes
LGTM

2022-07-04 07:45 UTC, merged